server:
    port: 8083

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://zipkin:9411
    cloud:
       gateway:
          routes:
            - id: passenger
              uri: lb://PASSENGER
              predicates:
                - Path=/api/v1/passengers/**

eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true